import { writable } from 'svelte/store';

// Create a writable store for language
export const currentLanguage = writable('ms'); // 'ms' for Malay, 'en' for English

// Language data
export const translations = {
  ms: {
    // Navigation
    'home': 'Laman Utama',
    'bookings': 'Tempahan',
    'contact_manager': 'Pengurus Kenalan',
    'settings': 'Tetapan',
    'context_manager': 'Pengurus Konteks',
    'add_context': 'Tambah Konteks',
    'booking_manager': 'Pengurus Tempahan',
    
    // Page Titles
    'page_title': 'Pengurus Kenalan',
    
    // Status Management
    'custom_status': 'Custom Status',
    'custom_status_description': 'Tambah, padam, dan ubah warna status',
    'add_status': 'Tambah Status',
    'reset_to_default': 'Reset ke Default',
    'status_updated': 'Status berjaya dikemas kini!',
    'status_added': 'Status baru berjaya ditambah!',
    'status_deleted': 'Status berjaya dipadam!',
    'reset_success': 'Status telah dikembalikan ke default!',
    
         // Dashboard
     'dashboard': 'Dashboard',
     'overview': 'Ringkasan aktiviti hari ini',
     'total_contacts': 'Jumlah Kenalan',
     'total_bookings': 'Jumlah Tempahan',
     'pending_bookings': 'Tempahan Tertunda',
     'new_contacts_today': 'Kenalan Baru Hari Ini',
    
         // Analytics
     'analytics': 'Analitik',
     'recent_booking': 'Tempahan Terkini',
     'recent_contacts': 'Kenalan Terkini',
     'no_bookings': 'Tiada tempahan baru',
     'no_income': 'Tiada pendapatan',
     'no_bookings_period': 'Belum ada tempahan untuk',
          'no_income_period': 'Belum ada pendapatan untuk',
     'yesterday': 'Semalam',
     'last_7_days': '7 Hari Lepas',
     'last_30_days': '30 Hari Lepas',
     
          // Common
     'my_account': 'Akaun Saya',
     'logout': 'Log Keluar',
     'language': 'Bahasa',
     
     // Booking Manager
     'booking_manager_title': 'Pengurus Tempahan',
     'add_new_booking': 'Tambah Tempahan Baru',
     'client_name': 'Nama Pelanggan',
     'date': 'Tarikh',
     'package_name': 'Nama Pakej',
     'amount': 'Jumlah',
     'status': 'Status',
     'actions': 'Tindakan',
     'completed': 'Selesai',
     'upcoming': 'Akan Datang',
     'past': 'Lepas',
     'today': 'Hari Ini',
     'upcoming_bookings': 'Tempahan Akan Datang',
     'drag_drop_instruction': '💡 Seret dan lepas card untuk mengubah status tempahan',
     'booking_moved': 'Tempahan "{name}" dipindahkan ke {status}',
     'delete': 'Padam',
     'cancel': 'Batal',
     'save': 'Simpan',
     'filter_all': 'Semua',
     'filter_completed': 'Selesai',
     'filter_upcoming': 'Akan Datang',
     'view_table': 'Senarai',
     'view_kanban': 'Kanban',
     'view_calendar': 'Kalendar',
     'view': 'Paparan',
     'search': 'Cari',
     'search_placeholder': 'Cari nama pelanggan atau pakej...',
     'filter': 'Penapis',
     'from': 'Dari',
     'to': 'Hingga',
     'batch_trash': 'Pindah ke Tong Sampah',
     'export': 'Eksport',
     'phone': 'Telefon',
     'enter_client_name': 'Masukkan nama pelanggan',
     'enter_phone': 'Masukkan nombor telefon',
     'enter_package_name': 'Masukkan nama pakej',
     'deal_by': 'Deal Oleh',
     'enter_deal_by': 'Pilih deal oleh',
     'booking_details': 'Butiran Tempahan',
     'edit': 'Sunting',
     'edit_booking': 'Sunting Tempahan',
     'close': 'Tutup',
     'prev': 'Sebelum',
     'next': 'Seterus',
     'page': 'Halaman',
     'bookings': 'tempahan',
     'no_bookings_message': 'Tiada tempahan dijumpai. Cuba ubah penapis atau tambah tempahan baru.',
     'choose_contact': 'Pilih Kontak',
     'choose_employee': 'Pilih Pekerja',
     'choose_package': 'Pilih Paket',
     'employee': 'Pekerja',
     'select_all': 'Pilih semua',
     'selected': 'dipilih',
     'delete_selected': 'Hapus Terpilih',
     'choose_date': 'Pilih tanggal',
     'loading': 'Memuat...',
     'refresh': 'Refresh',
     'new_bookings': 'Tempahan Baru',
     'income': 'Pendapatan',
     'active_customers': 'Pelanggan Aktif',
     'cancelled_bookings': 'Tempahan Batal',
     'reload': 'Muat Ulang',
     'failed_load_stats': 'Gagal memuat statistik dashboard',
     'status_baru': 'Status Baru',
     'dalam_proses': 'Dalam Proses',
     'selesai': 'Selesai',
     'keyboard_shortcuts': '⌨️ Pintasan Papan Kekunci:',
     'tambah_booking': 'Tambah Tempahan',
     'refresh_data': 'Muat Semula Data',
     'tutup_modal': 'Tutup Modal',
     'tukar_tampilan': 'Tukar tampilan',
     'tampilan_senarai': 'Tampilan Senarai',
     'tampilan_kanban': 'Tampilan Kanban',
     'tampilan_kalendar': 'Tampilan Kalendar',
     'no_bookings_in_system': 'Belum ada tempahan dalam sistem. Klik "Tambah Tempahan Baru" untuk mula.',
     'no_bookings_title': 'Belum Ada Tempahan',
     'no_bookings_description': 'Belum ada tempahan yang tersimpan di sistem.',
     'no_bookings_found': 'Tiada Tempahan Dijumpai',
     'add_first_booking': 'Tambah Tempahan Pertama',
     'status_changed': 'Status tempahan diubah ke: {status}',
     'try_again': 'Coba Lagi',
     'loading_bookings': 'Memuat data tempahan...',
     'please_wait': 'Mohon tunggu sebentar',
     'no_bookings_match_filter': 'Tiada Tempahan Memenuhi Filter',
     'bookings_in_system': 'Terdapat {count} tempahan di sistem, tetapi tiada yang memenuhi kriteria filter semasa.',
     'reset_filter': 'Reset Penapis',
     'add_new_booking': 'Tambah Tempahan Baru',
     'bulk_actions': 'Tindakan',
     'confirm_delete': 'Konfirmasi Hapus',
     'add_booking': 'Tambah Tempahan',
     'action_cannot_be_undone': 'Tindakan ini tidak dapat dibatalkan',
     'failed_change_status': 'Gagal mengubah status tempahan. Coba lagi.',
     'rescheduled': 'Dijadualkan Semula',
          'no_show': 'Tidak Hadir',
     'insights': 'Wawasan',
     'card_view': 'Tampilan Kartu',
     'table_view': 'Tampilan Tabel',
     'add_contact': 'Tambah Kenalan',
     'card': 'Kad',
     'table': 'Senarai',
     'switch_view': 'Tukar tampilan',
     'select_all': 'Pilih semua',
     'selected': 'dipilih',
     'delete_selected': 'Hapus Terpilih',
     'add_new_contact': 'Tambah Kenalan Baru',
     'name': 'Nama',
     'whatsapp': 'WhatsApp',
     'email': 'Email',
     'optional': 'Opsional',
     'enter_name': 'Masukkan nama',
     'enter_whatsapp': 'Masukkan nombor WhatsApp',
     'enter_email': 'Masukkan email',
     'only_numbers_allowed': 'Hanya nombor yang dibenarkan (maksimum 15 digit)',
     'cancel': 'Batal',
     'save_contact': 'Simpan Kenalan',
     'try_again': 'Coba Lagi',
     'loading_contacts': 'Memuat kontak...',
     'no_contacts': 'Tiada kenalan lagi',
     'click_add_contact': 'Klik "Tambah Kenalan" untuk menambah kenalan pertama anda',
     'view': 'Lihat',
     'edit': 'Sunting',
     'delete': 'Padam',
     'select': 'Pilih',
     'actions': 'Aksi',
     'contact_details': 'Detail Kenalan',
     'close': 'Tutup',
     'edit_contact': 'Edit Kenalan',
     'save_changes': 'Simpan Perubahan',
     'failed_load_contacts': 'Gagal memuat data kontak. Silakan coba lagi.',
     'failed_add_contact': 'Gagal menambah kontak. Silakan coba lagi.',
     'failed_update_contact': 'Gagal memperbarui kontak. Silakan coba lagi.',
     'failed_delete_contact': 'Gagal menghapus kontak. Silakan coba lagi.',
     'failed_delete_selected': 'Gagal menghapus kontak terpilih. Silakan coba lagi.',
     'settings_title': 'Tetapan',
     'brand_info': 'Maklumat Brand',
     'brand_info_description': 'Tetapkan nama brand/syarikat anda',
     'brand_name': 'Nama Brand',
     'enter_brand_name': 'Masukkan nama brand',
     'date_availability_settings': 'Tetapan Ketersediaan Tarikh',
     'date_availability_description': 'Tetapkan hari dan masa yang tersedia untuk tempahan',
     'start': 'Mula:',
     'end': 'Tamat:',
     'save_availability': 'Simpan Ketersediaan',
     'holiday_management': 'Pengurusan Cuti',
     'holiday_management_description': 'Tambah dan urus tarikh cuti',
     'date': 'Tarikh',
     'description': 'Keterangan',
     'add_holiday': 'Tambah Cuti',
     'loading_settings': 'Memuat tetapan...',
     'holiday': 'Cuti',
     'not_holiday': 'Bukan Cuti',
     'holiday_list': 'Senarai Cuti',
     'no_holidays_for_month': 'Tiada cuti untuk {month} {year}',
     'delete_holiday': 'Padam cuti',
     'status_name': 'Nama status',
     'color_for_status': 'Warna untuk {name}',
     'delete_status': 'Padam status',
     'packages_pricing': 'Pakej & Harga',
     'packages_description': 'Tambah, padam, dan ubah nama serta harga pakej',
     'package_name': 'Nama pakej',
     'add_package': 'Tambah Pakej',
     'delete_package': 'Padam pakej',
     'holiday_added_success': 'Cuti berjaya ditambah!',
     'holiday_added_failed': 'Gagal menambah cuti. Cuba lagi.',
     'holiday_deleted_success': 'Cuti berjaya dipadam!',
     'holiday_deleted_failed': 'Gagal memadam cuti. Cuba lagi.'
   },
   en: {
    // Navigation
    'home': 'Home',
    'booking_manager': 'Booking Manager',
    'contact_manager': 'Contact Manager',
    'settings': 'Settings',
    'context_manager': 'Context Manager',
    'add_context': 'Add Context',
    
    // Page Titles
    'page_title': 'Contact Manager',
    
    // Status Management
    'custom_status': 'Custom Status',
    'custom_status_description': 'Add, delete, and modify status colors',
    'add_status': 'Add Status',
    'reset_to_default': 'Reset to Default',
    'status_updated': 'Status updated successfully!',
    'status_added': 'New status added successfully!',
    'status_deleted': 'Status deleted successfully!',
    'reset_success': 'Status reset to default successfully!',
    
    // Dashboard
    'dashboard': 'Dashboard',
    'overview': 'Today\'s activity overview',
    'total_contacts': 'Total Contacts',
    'total_bookings': 'Total Bookings',
    'pending_bookings': 'Pending Bookings',
    'new_contacts_today': 'New Contacts Today',
    
    // Analytics
    'analytics': 'Analytics',
    'recent_booking': 'Recent Booking',
    'recent_contacts': 'Recent Contacts',
    'no_bookings': 'No new bookings',
    'no_income': 'No income',
    'no_bookings_period': 'No bookings for',
         'no_income_period': 'No income for',
     'yesterday': 'Yesterday',
     'last_7_days': 'Last 7 days',
     'last_30_days': 'Last 30 days',
     
          // Common
     'my_account': 'My Account',
     'logout': 'Logout',
     'language': 'Language',
     
     // Booking Manager
     'booking_manager_title': 'Booking Manager',
     'add_new_booking': 'Add New Booking',
     'bulk_actions': 'Actions',
     'client_name': 'Client Name',
     'date': 'Date',
     'package_name': 'Package Name',
     'amount': 'Amount',
     'status': 'Status',
     'actions': 'Actions',
     'completed': 'Completed',
     'upcoming': 'Upcoming',
     'past': 'Past',
     'today': 'Today',
     'upcoming_bookings': 'Upcoming Bookings',
     'drag_drop_instruction': '💡 Drag and drop cards to change booking status',
     'booking_moved': 'Booking "{name}" moved to {status}',
     'delete': 'Delete',
     'cancel': 'Cancel',
     'save': 'Save',
     'filter_all': 'All',
     'filter_completed': 'Completed',
     'filter_upcoming': 'Upcoming',
     'view_table': 'Table',
     'view_kanban': 'Kanban',
     'view_calendar': 'Calendar',
     'view': 'View',
     'search': 'Search',
     'search_placeholder': 'Search client name or package...',
     'filter': 'Filter',
     'from': 'From',
     'to': 'To',
     'batch_trash': 'Move to Trash',
     'export': 'Export',
     'phone': 'Phone',
     'enter_client_name': 'Enter client name',
     'enter_phone': 'Enter phone number',
     'enter_package_name': 'Enter package name',
     'deal_by': 'Deal By',
     'enter_deal_by': 'Select deal by',
     'booking_details': 'Booking Details',
     'edit': 'Edit',
     'edit_booking': 'Edit Booking',
     'close': 'Close',
     'prev': 'Previous',
     'next': 'Next',
     'page': 'Page',
     'bookings': 'bookings',
     'no_bookings_message': 'No bookings found. Try changing filters or add a new booking.',
     'choose_contact': 'Choose Contact',
     'choose_employee': 'Choose Employee',
     'choose_package': 'Choose Package',
     'employee': 'Employee',
     'select_all': 'Select all',
     'selected': 'selected',
     'delete_selected': 'Delete selected',
     'choose_date': 'Choose date',
     'loading': 'Loading...',
     'refresh': 'Refresh',
     'new_bookings': 'New Bookings',
     'income': 'Income',
     'active_customers': 'Active Customers',
     'cancelled_bookings': 'Cancelled Bookings',
     'reload': 'Reload',
     'failed_load_stats': 'Failed to load dashboard statistics',
     'status_baru': 'New Status',
     'dalam_proses': 'In Progress',
     'selesai': 'Completed',
     'keyboard_shortcuts': '⌨️ Keyboard Shortcuts:',
     'tambah_booking': 'Add Booking',
     'refresh_data': 'Refresh Data',
     'tutup_modal': 'Close Modal',
     'tukar_tampilan': 'Switch view',
     'tampilan_senarai': 'List View',
     'tampilan_kanban': 'Kanban View',
     'tampilan_kalendar': 'Calendar View',
     'no_bookings_in_system': 'No bookings in the system. Click "Add New Booking" to start.',
     'no_bookings_title': 'No Bookings',
     'no_bookings_description': 'No bookings saved in the system.',
     'no_bookings_found': 'No Bookings Found',
     'add_first_booking': 'Add First Booking',
     'status_changed': 'Booking status changed to: {status}',
     'try_again': 'Try Again',
     'loading_bookings': 'Loading booking data...',
     'please_wait': 'Please wait a moment',
     'no_bookings_match_filter': 'No Bookings Match Filter',
     'bookings_in_system': 'There are {count} bookings in the system, but none match the current filter criteria.',
     'reset_filter': 'Reset Filter',
     'confirm_delete': 'Confirm Delete',
     'add_booking': 'Add Booking',
     'action_cannot_be_undone': 'This action cannot be undone',
     'failed_change_status': 'Failed to change booking status. Please try again.',
     'rescheduled': 'Rescheduled',
     'no_show': 'No Show',
     'insights': 'Insights',
     'card_view': 'Card View',
     'table_view': 'Table View',
     'add_contact': 'Add Contact',
          'card': 'Card',
     'table': 'Table',
     'switch_view': 'Switch view',
     'select_all': 'Select all',
     'selected': 'selected',
     'delete_selected': 'Delete Selected',
     'add_new_contact': 'Add New Contact',
     'name': 'Name',
     'whatsapp': 'WhatsApp',
     'email': 'Email',
     'optional': 'Optional',
     'enter_name': 'Enter name',
     'enter_whatsapp': 'Enter WhatsApp number',
     'enter_email': 'Enter email',
     'only_numbers_allowed': 'Only numbers allowed (maximum 15 digits)',
     'cancel': 'Cancel',
     'save_contact': 'Save Contact',
     'try_again': 'Try Again',
     'loading_contacts': 'Loading contacts...',
     'no_contacts': 'No contacts yet',
     'click_add_contact': 'Click "Add Contact" to add your first contact',
     'view': 'View',
     'edit': 'Edit',
     'delete': 'Delete',
     'select': 'Select',
     'actions': 'Actions',
     'contact_details': 'Contact Details',
     'close': 'Close',
     'edit_contact': 'Edit Contact',
     'save_changes': 'Save Changes',
     'failed_load_contacts': 'Failed to load contact data. Please try again.',
     'failed_add_contact': 'Failed to add contact. Please try again.',
     'failed_update_contact': 'Failed to update contact. Please try again.',
     'failed_delete_contact': 'Failed to delete contact. Please try again.',
     'failed_delete_selected': 'Failed to delete selected contacts. Please try again.',
     'settings_title': 'Settings',
     'brand_info': 'Brand Information',
     'brand_info_description': 'Set your brand/company name',
     'brand_name': 'Brand Name',
     'enter_brand_name': 'Enter brand name',
     'date_availability_settings': 'Date Availability Settings',
     'date_availability_description': 'Set available days and times for bookings',
     'start': 'Start:',
     'end': 'End:',
     'save_availability': 'Save Availability',
     'holiday_management': 'Holiday Management',
     'holiday_management_description': 'Add and manage holidays',
     'date': 'Date',
     'description': 'Description',
     'add_holiday': 'Add Holiday',
     'loading_settings': 'Loading settings...',
     'holiday': 'Holiday',
     'not_holiday': 'Not a Holiday',
     'holiday_list': 'Holiday List',
     'no_holidays_for_month': 'No holidays for {month} {year}',
     'delete_holiday': 'Delete Holiday',
     'status_name': 'Status Name',
     'color_for_status': 'Color for {name}',
     'delete_status': 'Delete Status',
     'packages_pricing': 'Packages & Pricing',
     'packages_description': 'Add, delete, and modify package names and prices',
     'package_name': 'Package Name',
     'add_package': 'Add Package',
     'delete_package': 'Delete Package',
     'holiday_added_success': 'Holiday added successfully!',
     'holiday_added_failed': 'Failed to add holiday. Please try again.',
     'holiday_deleted_success': 'Holiday deleted successfully!',
     'holiday_deleted_failed': 'Failed to delete holiday. Please try again.'
   }
 };

// Function to get translation
export function t(key) {
  const current = currentLanguage.get();
  return translations[current]?.[key] || key;
}

// Function to toggle language
export function toggleLanguage() {
  const current = currentLanguage.get();
  currentLanguage.set(current === 'ms' ? 'en' : 'ms');
} 